branches:
    only:
        - master
        - /^v\d/

notifications:
        email: false

sudo: required

language: perl

dist: trusty

perl:
    - "5.10"
    - "5.14"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"

before_install:
    - sudo apt-get update
    - sudo apt-get install -y glusterfs-server glusterfs-client libacl1 attr
    - sudo dpkg-query -L glusterfs-server
    - sudo dpkg-query -L glusterfs-client

install:
    - cpanm -quiet --notest --skip-satisfied --installdeps .

script:
    - perl .TRAVIS.PL
